from_pretrained: null

run_name: ffhq_faces
run_id: v1
hf_repo: null # repo to of pretrained model to train off of

ckpt_dir: model_ckpts

dataset: idning/ffhq256-caption
img_label: image 
text_label: text
num_workers: 4
pixel_h: 256
pixel_w: 256

vae: REPA-E/e2e-sdvae-hf
vae_downsample_factor: 8
vae_scale_factor: 0.18215

batch_size: 96
iterations: 50000
log_steps: 10
checkpoint_steps: 2000

num_devices: 1

embed_dims: 768
head_size: 64
block_num: 16

patch_size: 2
out_channels: 4
in_dims: 4

lr: 1e-4
acc_grad: 1
