run_name: anime_faces
run_id: 1
hf_repo: Jumpr/anime-face-checkpoints

ckpt_dir: model_ckpts

dataset: minoruskore/anime-faces-256
num_workers: 8
pixel_h: 256
pixel_w: 256

vae: REPA-E/e2e-sdvae-hf
vae_downsample_factor: 8
vae_scale_factor: 0.18215

batch_size: 24
iterations: 500000
log_steps: 50
checkpoint_steps: 1000

num_devices: 1

embed_dims: 768
head_size: 64
block_num: 16

patch_size: 2
out_channels: 4
in_dims: 4

lr: 1e-4
acc_grad: 1